"""Initial modular migration

Revision ID: 956201f6b4ac
Revises: 
Create Date: 2026-03-16 17:32:16.220240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '956201f6b4ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'preferred_language',
               existing_type=mysql.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'fr'"))
    op.alter_column('profile', 'experience_level',
               existing_type=mysql.VARCHAR(length=50),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profile', 'current_goal',
               existing_type=mysql.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('profile', 'weak_points',
               existing_type=mysql.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'weak_points',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('profile', 'current_goal',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('profile', 'experience_level',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('profile', 'preferred_language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'fr'"))
    # ### end Alembic commands ###
